-- =====================================================================
--  KirpichMusic — PostgreSQL schema  (миграция 001 — initial)
--  Target: PostgreSQL >= 13 (рекомендуется 15+)
--  Encoding: UTF-8, server_timezone: UTC
--  Совместимость: Linux, OpenBSD (расширения citext / pg_trgm / pgcrypto
--  входят в стандартный postgresql-contrib на обеих ОС).
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
--  Расширения
-- ---------------------------------------------------------------------
--  citext   — регистронезависимые email / username без функциональных индексов
--  pgcrypto — gen_random_uuid() для session_id (ШАГ 2)
--  pg_trgm  — GIN-индекс для быстрого ILIKE-поиска по названиям треков
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ---------------------------------------------------------------------
--  Утилитарный триггер updated_at (один раз — переиспользуется везде)
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =====================================================================
--  USERS
-- =====================================================================
CREATE TABLE users (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- В UI логин возможен по email ИЛИ по имени (см. doLogin),
    -- поэтому оба поля уникальны и регистронезависимы (CITEXT).
    username        CITEXT       NOT NULL UNIQUE,
    email           CITEXT       NOT NULL UNIQUE,

    -- ВАЖНО: храним ТОЛЬКО хеш (Argon2id PHC-строка ~96 байт, либо bcrypt $2b$...).
    -- Никогда не храним пароль в открытом виде.
    password_hash   TEXT         NOT NULL,

    display_name    TEXT,
    bio             TEXT,
    avatar_path     TEXT,        -- относительный путь к файлу аватарки на диске

    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- Минимальные DB-инварианты (защита от мусора, даже если приложение ошибётся)
    CONSTRAINT users_username_len   CHECK (char_length(username) BETWEEN 2 AND 32),
    CONSTRAINT users_username_chars CHECK (username ~ '^[A-Za-z0-9_.\- ]+$'),
    CONSTRAINT users_email_format   CHECK (email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
    CONSTRAINT users_pwhash_nonempty CHECK (char_length(password_hash) >= 20)
);

CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- UNIQUE-ограничения уже создали индексы по username и email — отдельные не нужны.

-- =====================================================================
--  TRACKS
-- =====================================================================
CREATE TABLE tracks (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Кто загрузил.
    -- ВНИМАНИЕ к политике удаления:
    --   ON DELETE SET NULL — при удалении аккаунта треки НЕ удаляются автоматически,
    --   uploader_id становится NULL ("осиротевший" трек, в UI — "Удалённый аккаунт").
    -- Если пользователь в форме удаления аккаунта поставит галочку "удалить и мои треки",
    -- приложение делает явный DELETE FROM tracks WHERE uploader_id = $1 ДО удаления юзера.
    uploader_id     BIGINT       REFERENCES users(id) ON DELETE SET NULL,

    title           TEXT         NOT NULL,
    -- Имя артиста как его указал юзер при загрузке (может отличаться от username).
    artist_name     TEXT         NOT NULL,
    genre           TEXT,

    duration_sec    INTEGER      NOT NULL CHECK (duration_sec >= 0),

    -- ----- Файлы хранятся НА ДИСКЕ, в БД только метаданные -----
    -- audio_path: относительный путь от media-root (например 'audio/2026/05/abc123.mp3').
    -- audio_mime определяется на сервере по содержимому (magic bytes), не по расширению!
    audio_path      TEXT         NOT NULL,
    audio_mime      TEXT         NOT NULL,
    audio_bytes     BIGINT       NOT NULL CHECK (audio_bytes > 0),

    cover_path      TEXT,        -- NULL → используем cover_color/cover_emoji как fallback
    cover_mime      TEXT,
    cover_bytes     BIGINT,

    -- Fallback-обложка, как в прототипе (DEMO_TRACKS)
    cover_color     TEXT,        -- '#4CAF50'
    cover_emoji     TEXT,        -- '🐷'

    -- Денормализованные счётчики (ускоряют сортировки / выдачу карточки трека).
    -- Источник истины: таблицы likes / comments + отдельный счётчик plays.
    -- Поддерживаются триггерами ниже.
    plays_count     BIGINT       NOT NULL DEFAULT 0 CHECK (plays_count >= 0),
    likes_count     BIGINT       NOT NULL DEFAULT 0 CHECK (likes_count >= 0),
    comments_count  BIGINT       NOT NULL DEFAULT 0 CHECK (comments_count >= 0),

    is_published    BOOLEAN      NOT NULL DEFAULT TRUE,

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT tracks_title_len    CHECK (char_length(title)       BETWEEN 1 AND 200),
    CONSTRAINT tracks_artist_len   CHECK (char_length(artist_name) BETWEEN 1 AND 120),
    CONSTRAINT tracks_audio_mime   CHECK (audio_mime IN (
        'audio/mpeg',           -- MP3
        'audio/wav','audio/x-wav','audio/wave',
        'audio/flac','audio/x-flac',
        'audio/aac','audio/mp4','audio/x-m4a',
        'audio/ogg'
    )),
    CONSTRAINT tracks_cover_mime   CHECK (cover_mime IS NULL OR cover_mime IN (
        'image/jpeg','image/png','image/webp'
    )),
    -- Список жанров — тот же, что в <select> из uploadModal
    CONSTRAINT tracks_genre_chk    CHECK (
        genre IS NULL OR genre IN (
            'Electronic','Hip-Hop','Rock','Pop','Jazz',
            'Classical','Ambient','Lo-fi','Другое'
        )
    )
);

CREATE TRIGGER tracks_set_updated_at
BEFORE UPDATE ON tracks
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------- Индексы под основные сценарии UI ----------
-- 1) Лента "Недавние" (renderRecentList — сортировка по дате DESC)
CREATE INDEX idx_tracks_created_at_desc
    ON tracks (created_at DESC)
    WHERE is_published = TRUE;

-- 2) Лента "Популярное" (renderPopularGrid)
CREATE INDEX idx_tracks_plays_desc
    ON tracks (plays_count DESC)
    WHERE is_published = TRUE;

CREATE INDEX idx_tracks_likes_desc
    ON tracks (likes_count DESC)
    WHERE is_published = TRUE;

-- 3) Профиль / "Мои треки" (renderProfile, фильтр own)
CREATE INDEX idx_tracks_uploader_created
    ON tracks (uploader_id, created_at DESC);

-- 4) Фильтр по жанру
CREATE INDEX idx_tracks_genre
    ON tracks (genre)
    WHERE genre IS NOT NULL AND is_published = TRUE;

-- 5) Поиск по названию/артисту (handleSearch — ILIKE %q%)
CREATE INDEX idx_tracks_title_trgm
    ON tracks USING gin (title gin_trgm_ops);

CREATE INDEX idx_tracks_artist_trgm
    ON tracks USING gin (artist_name gin_trgm_ops);

-- =====================================================================
--  COMMENTS
-- =====================================================================
CREATE TABLE comments (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_id    BIGINT       NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
    user_id     BIGINT       NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    body        TEXT         NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT comments_body_len CHECK (char_length(body) BETWEEN 1 AND 1000)
);

CREATE TRIGGER comments_set_updated_at
BEFORE UPDATE ON comments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- "Все комменты к треку, новые сверху" — самый частый запрос (renderComments)
CREATE INDEX idx_comments_track_created  ON comments (track_id, created_at DESC);
-- "Комменты пользователя" — для будущей вкладки в профиле
CREATE INDEX idx_comments_user_created   ON comments (user_id,  created_at DESC);

-- Поддержка денормализованного comments_count в tracks
CREATE OR REPLACE FUNCTION trg_comments_count()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE tracks SET comments_count = comments_count + 1
         WHERE id = NEW.track_id;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE tracks SET comments_count = GREATEST(comments_count - 1, 0)
         WHERE id = OLD.track_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER comments_count_trg
AFTER INSERT OR DELETE ON comments
FOR EACH ROW EXECUTE FUNCTION trg_comments_count();

-- =====================================================================
--  LIKES   (M:N user <-> track, источник истины для likes_count)
-- =====================================================================
CREATE TABLE likes (
    user_id     BIGINT       NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    track_id    BIGINT       NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- Один юзер может лайкнуть один трек ровно 1 раз
    PRIMARY KEY (user_id, track_id)
);

-- Composite PK эффективен только по leftmost-prefix (user_id).
-- Для запроса "сколько/кто лайкнул трек X" нужен обратный индекс:
CREATE INDEX idx_likes_track_created  ON likes (track_id, created_at DESC);

-- Поддержка денормализованного likes_count в tracks
CREATE OR REPLACE FUNCTION trg_likes_count()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE tracks SET likes_count = likes_count + 1
         WHERE id = NEW.track_id;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE tracks SET likes_count = GREATEST(likes_count - 1, 0)
         WHERE id = OLD.track_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER likes_count_trg
AFTER INSERT OR DELETE ON likes
FOR EACH ROW EXECUTE FUNCTION trg_likes_count();

-- =====================================================================
--  SESSIONS  (опционально — задел под ШАГ 2: HttpOnly-cookie сессии)
--  Если выберем JWT + refresh, эту таблицу заменит refresh_tokens —
--  структура почти идентична (token_hash, user_id, expires_at, revoked_at).
-- =====================================================================
CREATE TABLE sessions (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- В куку отдаём сырой session_id; в БД хранится только SHA-256/HMAC.
    -- Даже при утечке дампа БД злоумышленник не сможет угнать сессии.
    token_hash    BYTEA        NOT NULL UNIQUE,

    user_agent    TEXT,
    ip_inet       INET,

    expires_at    TIMESTAMPTZ  NOT NULL,
    revoked_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_sessions_user        ON sessions (user_id);
-- Частичный индекс — отбрасывает уже отозванные сессии,
-- ускоряет фоновую очистку по expires_at.
CREATE INDEX idx_sessions_expires_at  ON sessions (expires_at) WHERE revoked_at IS NULL;

COMMIT;
