-- =====================================================================
--  KirpichMusic — миграция 003
--  Добавляет:
--    1) playlists                — пользовательские подборки треков
--    2) playlist_tracks          — m:n с явной позицией для порядка
--    3) trg_playlist_tracks_count — авто-поддержка playlists.tracks_count
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
--  1) Плейлисты
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS playlists (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title         TEXT         NOT NULL,
    description   TEXT,
    cover_color   TEXT         NOT NULL DEFAULT '#1a1a2e',
    cover_emoji   TEXT         NOT NULL DEFAULT '🎵',
    is_public     BOOLEAN      NOT NULL DEFAULT TRUE,
    tracks_count  INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT playlists_title_len      CHECK (char_length(title) BETWEEN 1 AND 80),
    CONSTRAINT playlists_descr_len      CHECK (description IS NULL OR char_length(description) <= 500),
    CONSTRAINT playlists_color_format   CHECK (cover_color ~* '^#[0-9a-f]{6}$'),
    CONSTRAINT playlists_count_nonneg   CHECK (tracks_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_playlists_user
    ON playlists (user_id, created_at DESC);

-- Публичные плейлисты могут отображаться в каталоге.
CREATE INDEX IF NOT EXISTS idx_playlists_public_recent
    ON playlists (created_at DESC)
    WHERE is_public = TRUE;

DROP TRIGGER IF EXISTS playlists_set_updated_at ON playlists;
CREATE TRIGGER playlists_set_updated_at
BEFORE UPDATE ON playlists
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
--  2) Связь "трек в плейлисте"
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS playlist_tracks (
    playlist_id   BIGINT       NOT NULL REFERENCES playlists(id) ON DELETE CASCADE,
    track_id      BIGINT       NOT NULL REFERENCES tracks(id)    ON DELETE CASCADE,
    position      INTEGER      NOT NULL,
    added_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    PRIMARY KEY (playlist_id, track_id)
);

CREATE INDEX IF NOT EXISTS idx_playlist_tracks_pos
    ON playlist_tracks (playlist_id, position);

-- ---------------------------------------------------------------------
--  3) Авто-обновление playlists.tracks_count + updated_at
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_playlist_tracks_count()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE playlists
           SET tracks_count = tracks_count + 1,
               updated_at   = now()
         WHERE id = NEW.playlist_id;
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE playlists
           SET tracks_count = GREATEST(0, tracks_count - 1),
               updated_at   = now()
         WHERE id = OLD.playlist_id;
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS playlist_tracks_count_ins ON playlist_tracks;
CREATE TRIGGER playlist_tracks_count_ins
AFTER INSERT ON playlist_tracks
FOR EACH ROW EXECUTE FUNCTION trg_playlist_tracks_count();

DROP TRIGGER IF EXISTS playlist_tracks_count_del ON playlist_tracks;
CREATE TRIGGER playlist_tracks_count_del
AFTER DELETE ON playlist_tracks
FOR EACH ROW EXECUTE FUNCTION trg_playlist_tracks_count();

COMMIT;
