-- =====================================================================
--  KirpichMusic — миграция 006
--  Профили исполнителей.
--  Артист — ОТДЕЛЬНАЯ сущность от пользователя:
--    * у артиста есть имя (CITEXT — анти-дубль на уровне БД), slug, описание,
--      аватар и шапка;
--    * один трек ссылается на одного артиста (`tracks.artist_id`);
--    * артист может быть «привязан» к user'у — `claimed_by_user_id`.
--      Только привязанный юзер и админы заливают в этот профиль напрямую,
--      остальные через очередь модерации (миграция 007).
--  Старое текстовое поле `tracks.artist_name` сохраняется (для отображения
--  и обратной совместимости — хотя в реальности тоже синхронизируется
--  с `artists.name`).
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
--  ARTISTS
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS artists (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- CITEXT гарантирует регистронезависимый UNIQUE: 'Король и Шут' и
    -- 'король и шут' — один артист. Это и есть анти-дубль.
    name                CITEXT       NOT NULL UNIQUE,

    -- slug — машиночитаемый идентификатор для URL-ов /artist/<slug>.
    -- Генерируется из name на уровне приложения (lowercase + замена
    -- небуквенно-нецифровых на дефис; кириллица транслитерируется).
    -- Пустой slug допустим только если приложение не смогло его сгенерить —
    -- тогда фронт открывает по id.
    slug                TEXT         UNIQUE,

    description         TEXT,

    avatar_path         TEXT,
    avatar_mime         TEXT,
    avatar_bytes        BIGINT,

    banner_path         TEXT,
    banner_mime         TEXT,
    banner_bytes        BIGINT,

    -- Верификация: к какому пользователю «привязан» этот профиль артиста.
    --   NULL = unclaimed (любой может заливать треки и предлагать аватары).
    --   ≠ NULL = claimed (только этот юзер и админы заливают напрямую).
    -- ON DELETE SET NULL: удаление юзера не должно убивать профиль артиста —
    -- профиль становится unclaimed.
    claimed_by_user_id  BIGINT       REFERENCES users(id) ON DELETE SET NULL,

    -- Дублирующий флаг для удобства запросов и UI-бейджа «✓».
    -- Поддерживается приложением: при выставлении claimed_by_user_id → TRUE.
    is_verified         BOOLEAN      NOT NULL DEFAULT FALSE,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT artists_name_len     CHECK (char_length(name) BETWEEN 1 AND 120),
    CONSTRAINT artists_slug_chars   CHECK (slug IS NULL OR slug ~ '^[a-z0-9][a-z0-9-]{0,119}$'),
    CONSTRAINT artists_avatar_mime  CHECK (avatar_mime IS NULL OR avatar_mime IN ('image/jpeg','image/png','image/webp')),
    CONSTRAINT artists_banner_mime  CHECK (banner_mime IS NULL OR banner_mime IN ('image/jpeg','image/png','image/webp'))
);

DROP TRIGGER IF EXISTS artists_set_updated_at ON artists;
CREATE TRIGGER artists_set_updated_at
BEFORE UPDATE ON artists
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Триграммный индекс — для быстрого «возможно вы имели в виду…».
CREATE INDEX IF NOT EXISTS idx_artists_name_trgm
    ON artists USING gin (name gin_trgm_ops);

-- Поиск по claimed-юзеру (для админки и проверок прав).
CREATE INDEX IF NOT EXISTS idx_artists_claimed
    ON artists (claimed_by_user_id) WHERE claimed_by_user_id IS NOT NULL;

-- ---------------------------------------------------------------------
--  TRACKS  → ссылка на artists
-- ---------------------------------------------------------------------
ALTER TABLE tracks
    ADD COLUMN IF NOT EXISTS artist_id BIGINT REFERENCES artists(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_tracks_artist_id
    ON tracks (artist_id) WHERE is_published = TRUE;

-- ---------------------------------------------------------------------
--  Backfill: создаём артистов из существующих треков и линкуем.
--  Идемпотентно: ON CONFLICT DO NOTHING + апдейт только тех треков,
--  у которых artist_id ещё NULL.
-- ---------------------------------------------------------------------
INSERT INTO artists (name)
SELECT DISTINCT artist_name
FROM tracks
WHERE artist_name IS NOT NULL
  AND char_length(artist_name) BETWEEN 1 AND 120
ON CONFLICT (name) DO NOTHING;

UPDATE tracks t
SET artist_id = a.id
FROM artists a
WHERE t.artist_id IS NULL
  AND t.artist_name = a.name;   -- CITEXT: регистр не важен

-- Backfill slug для ASCII-имён (для кириллицы slug делает приложение
-- через MakeSlug — оно с транслитерацией, а в SQL её делать тяжело).
UPDATE artists
   SET slug = LOWER(
       regexp_replace(
         regexp_replace(name::TEXT, '[^a-zA-Z0-9]+', '-', 'g'),
         '(^-+|-+$)', '', 'g'
       )
   )
 WHERE slug IS NULL
   AND name::TEXT ~ '^[A-Za-z0-9 _-]+$'
   AND LOWER(regexp_replace(regexp_replace(name::TEXT, '[^a-zA-Z0-9]+', '-', 'g'), '(^-+|-+$)', '', 'g')) ~ '^[a-z0-9][a-z0-9-]{0,119}$';

COMMIT;
