-- =====================================================================
--  KirpichMusic — миграция 007
--  Очереди модерации:
--    1) artist_avatar_proposals — народные предложения аватарок артистов;
--       одобряет админ.
--    2) tracks.moderation_status + tracks.moderated_by — флаг
--       «трек ждёт одобрения у claimed-артиста» (или у админа). Не отдельная
--       таблица — так проще, в публичных листингах фильтр по
--       moderation_status='approved' OR uploader == viewer.
--       Когда трек загружают на claimed-артиста и uploader != claimed_by/admin,
--       статус ставится 'pending'. Approve → 'approved' + is_published=TRUE,
--       reject → удаляем (и файл с диска).
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
--  ARTIST AVATAR PROPOSALS
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS artist_avatar_proposals (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    artist_id           BIGINT       NOT NULL REFERENCES artists(id) ON DELETE CASCADE,

    -- Кто предложил. ON DELETE SET NULL — если юзер удалил аккаунт,
    -- предложение остаётся в очереди (анонимизируется).
    proposed_by         BIGINT       REFERENCES users(id) ON DELETE SET NULL,

    image_path          TEXT         NOT NULL,
    image_mime          TEXT         NOT NULL,
    image_bytes         BIGINT       NOT NULL CHECK (image_bytes > 0),

    -- pending → admin не посмотрел.
    -- approved → принято: artists.avatar_path обновлён, файл предложения
    --            становится действующим аватаром (или копируется — на выбор приложения).
    -- rejected → не подошло; файл нужно удалить с диска.
    status              TEXT         NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending','approved','rejected')),

    note                TEXT,        -- комментарий админа, опционально

    reviewed_by         BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at         TIMESTAMPTZ,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT artist_avatar_proposals_mime CHECK (
        image_mime IN ('image/jpeg','image/png','image/webp')
    )
);

CREATE INDEX IF NOT EXISTS idx_artist_avatar_proposals_pending
    ON artist_avatar_proposals (created_at DESC)
    WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_artist_avatar_proposals_artist
    ON artist_avatar_proposals (artist_id, status, created_at DESC);

-- ---------------------------------------------------------------------
--  TRACKS  →  модерация (для claimed-артистов)
-- ---------------------------------------------------------------------
ALTER TABLE tracks
    ADD COLUMN IF NOT EXISTS moderation_status TEXT NOT NULL DEFAULT 'approved'
        CHECK (moderation_status IN ('approved','pending','rejected'));

ALTER TABLE tracks
    ADD COLUMN IF NOT EXISTS moderated_by BIGINT REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE tracks
    ADD COLUMN IF NOT EXISTS moderated_at TIMESTAMPTZ;

-- Очередь pending — нужна админу и claimed-артисту, чтобы видеть свои заявки.
CREATE INDEX IF NOT EXISTS idx_tracks_pending
    ON tracks (artist_id, created_at DESC)
    WHERE moderation_status = 'pending';

COMMIT;
